# Generated by Django 5.0.3 on 2024-04-11 09:25

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='decs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part_category',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
